version: '3.2'
volumes:
  postgres-data:
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: foreman start -f Procfile.dev -p 3000
    volumes:
      - .:/service
      - type: tmpfs
        target: /service/tmp/pids/
    ports:
      - "3000:3000"
    depends_on:
      - db
